const countryToJapanese = {
    "Afghanistan" : "アフガニスタン",
    "Albania" : "アルバニア",
    "Algeria"
    "Andorra"
    "Angola"
    "Antigua and Barbuda"
    "Argentina"
    "Armenia"
    "Australia"
    "Austria"
    "Azerbaijan"
    "Bahamas"
    "Bahrain"
    "Bangladesh"
    "Barbados"
    "Belarus"
    "Belgium"
    "Belize"
    "Benin"
    "Bhutan"
    "Bolivia"
    "Bosnia and Herzegovina"
    "Botswana"
    "Brazil"
    "Brunei"
    "Bulgaria"
    "Burkina Faso"
    "Burma"
    "Burundi"
    "Cabo Verde"
    "Cambodia"
    "Cameroon"
    "Canada"
    "Central African Republic"
    "Chad"
    "Chile"
    "China"
    "Colombia"
    "Comoros"
    "Congo (Brazzaville)"
    "Congo (Kinshasa)"
    "Costa Rica"
    "Cote d'Ivoire"
    "Croatia"
    "Cuba"
    "Cyprus"
    "Czechia"
}